#!python
compiler = 'gcc'
# Wall = turns all all warnings. g = generates dbug symbols
cppFlags = ['-Wall', '-g']
cxxFlags = ['-std=c++11']

libraries = ['SDL2', 'SDL2_ttf']

test_lib = ['gtest', 'gtest_main']

env = Environment(
    CXXFLAGS=cxxFlags,
    CC=compiler,
    CPPFLAGS=cppFlags,
    LIBS=[libraries])

test = env.Clone()

test.Append(LIBS=test_lib)
source = [
    'tictactoe.cpp',
    'text_renderer.cpp',
    'media_manager.cpp'
]

tests = [
    'test_board.cpp',
    'test_piece.cpp',
    'test_tictactoe.cpp'
]

unit_test = test.Program(target='test', source=[source, tests], LIBPATH='/usr/include/gtest')
test_alias = Alias('test', [unit_test], unit_test[0].abspath)
AlwaysBuild(test_alias)
env.Program(target='game', source=[source, 'tictactoe_main.cpp'])
