#!python
compiler = 'gcc'
cppFlags = ['-Wall']
cxxFlags = ['-std=c++11']

libraries = ['SDL2']

env = Environment(
    CXXFLAGS=cxxFlags,
    CC=compiler,
    CPPFLAGS=cppFlags,
    LIBS=libraries)

env.Program(target='test', source=['test.cpp'])

#SConscript('sketch/sconscript', exports='env')
